const storageKey = 'daymark-state';
const defaultState = { lists: [{ id: 'personal', name: 'Personal', color: 'peach' }, { id: 'work', name: 'Work', color: 'blue' }, { id: 'ideas', name: 'Ideas', color: 'yellow' }], tasks: [{ id: crypto.randomUUID(), title: 'Plan the week ahead', notes: 'Review priorities and make room for the things that matter.', listId: 'personal', due: nextDate(0), time: '09:00', completed: false, created: Date.now() - 400000 }, { id: crypto.randomUUID(), title: 'Send project update', notes: 'A quick note to the team with this week\'s progress.', listId: 'work', due: nextDate(1), time: '14:30', completed: false, created: Date.now() - 300000 }, { id: crypto.randomUUID(), title: 'Read for thirty minutes', notes: '', listId: 'ideas', due: nextDate(3), time: '', completed: true, created: Date.now() - 200000 }] };
let state = loadState();
let currentView = 'all';
let currentFilter = 'all';
let sortNewest = true;
let editingId = null;

function nextDate(offset) { const date = new Date(); date.setDate(date.getDate() + offset); return formatDateInput(date); }
function formatDateInput(date) { return new Date(date).toISOString().slice(0, 10); }
function loadState() { try { return JSON.parse(localStorage.getItem(storageKey)) || defaultState; } catch { return defaultState; } }
function saveState() { localStorage.setItem(storageKey, JSON.stringify(state)); }
function today() { return formatDateInput(new Date()); }
function dateLabel(dateString, time) { if (!dateString) return 'No date'; const date = new Date(`${dateString}T12:00:00`); const day = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }); const prefix = dateString === today() ? 'Today' : day; return time ? `${prefix} · ${formatTime(time)}` : prefix; }
function formatTime(time) { const [hour, minute] = time.split(':'); const date = new Date(); date.setHours(hour, minute); return date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }); }
function getList(id) { return state.lists.find(list => list.id === id) || { name: 'Unsorted', color: 'blue' }; }
function visibleTasks() { let tasks = [...state.tasks]; if (currentView === 'today') tasks = tasks.filter(task => task.due === today()); if (currentView === 'upcoming') tasks = tasks.filter(task => task.due && task.due > today()); if (currentView === 'completed') tasks = tasks.filter(task => task.completed); if (state.lists.some(list => list.id === currentView)) tasks = tasks.filter(task => task.listId === currentView); if (currentFilter === 'active') tasks = tasks.filter(task => !task.completed); if (currentFilter === 'completed') tasks = tasks.filter(task => task.completed); return tasks.sort((a, b) => sortNewest ? b.created - a.created : (a.due || '9999').localeCompare(b.due || '9999')); }
function render() { renderNavigation(); renderTasks(); renderStats(); document.getElementById('date-label').textContent = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }); }
function renderNavigation() { const open = state.tasks.filter(task => !task.completed); document.getElementById('all-count').textContent = open.length; document.getElementById('today-count').textContent = open.filter(task => task.due === today()).length; document.getElementById('upcoming-count').textContent = open.filter(task => task.due > today()).length; document.getElementById('completed-count').textContent = state.tasks.filter(task => task.completed).length; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === currentView)); document.getElementById('list-nav').innerHTML = state.lists.map(list => `<button class="list-nav-item ${list.id === currentView ? 'active' : ''}" data-view="${list.id}"><span class="list-dot"></span>${escapeHtml(list.name)}<span class="nav-count">${state.tasks.filter(task => task.listId === list.id && !task.completed).length}</span></button>`).join(''); document.querySelectorAll('[data-view]').forEach(item => item.addEventListener('click', () => { currentView = item.dataset.view; currentFilter = 'all'; updateHeading(); render(); })); }
function renderTasks() { const container = document.getElementById('task-list'); const tasks = visibleTasks(); if (!tasks.length) { container.innerHTML = `<div class="empty-state"><div class="empty-icon">✦</div><h3>Nothing here yet</h3><p>A clear space for your next little win.</p></div>`; return; } container.innerHTML = tasks.map((task, index) => { const list = getList(task.listId); return `<article class="task-row ${task.completed ? 'completed' : ''}" style="animation-delay:${index * 35}ms"><button class="check-button" data-complete="${task.id}" aria-label="Mark task ${task.completed ? 'active' : 'completed'}">${task.completed ? '✓' : ''}</button><div><p class="task-title">${escapeHtml(task.title)}</p>${task.notes ? `<p class="task-notes">${escapeHtml(task.notes)}</p>` : ''}<div class="task-meta"><span class="meta-pill">${escapeHtml(list.name)}</span><span>${dateLabel(task.due, task.time)}</span></div></div><button class="task-menu" data-edit="${task.id}" aria-label="Edit task">•••</button></article>`; }).join(''); document.querySelectorAll('[data-complete]').forEach(button => button.addEventListener('click', () => toggleTask(button.dataset.complete))); document.querySelectorAll('[data-edit]').forEach(button => button.addEventListener('click', () => openTaskModal(button.dataset.edit))); }
function renderStats() { const total = state.tasks.length; const done = state.tasks.filter(task => task.completed).length; const weekEnd = new Date(); weekEnd.setDate(weekEnd.getDate() + 7); document.getElementById('stat-open').textContent = total - done; document.getElementById('stat-done').textContent = `${total ? Math.round(done / total * 100) : 0}%`; document.getElementById('stat-due').textContent = state.tasks.filter(task => task.due && new Date(`${task.due}T12:00:00`) <= weekEnd && !task.completed).length; document.getElementById('title-count').textContent = visibleTasks().length; }
function updateHeading() { const labels = { all: 'All tasks', today: 'Today', upcoming: 'Upcoming', completed: 'Completed' }; const label = labels[currentView] || getList(currentView).name; document.getElementById('page-title').childNodes[0].textContent = `${label} `; document.getElementById('breadcrumb-label').textContent = label; }
function openTaskModal(id = null) { editingId = id; const task = state.tasks.find(item => item.id === id); document.getElementById('modal-title').textContent = task ? 'Edit task' : 'New task'; document.getElementById('task-name').value = task?.title || ''; document.getElementById('task-notes').value = task?.notes || ''; document.getElementById('task-date').value = task?.due || ''; document.getElementById('task-time').value = task?.time || ''; document.getElementById('task-list-select').innerHTML = state.lists.map(list => `<option value="${list.id}" ${list.id === (task?.listId || currentView) ? 'selected' : ''}>${escapeHtml(list.name)}</option>`).join(''); document.getElementById('delete-task').classList.toggle('hidden', !task); document.getElementById('task-modal').classList.remove('hidden'); document.getElementById('task-name').focus(); }
function closeModal() { document.getElementById('task-modal').classList.add('hidden'); editingId = null; }
function toggleTask(id) { const task = state.tasks.find(item => item.id === id); task.completed = !task.completed; saveState(); render(); showToast(task.completed ? 'Task completed' : 'Task reopened'); }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character])); }
function showToast(message) { const toast = document.getElementById('toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 1800); }
document.getElementById('new-task').addEventListener('click', () => openTaskModal()); document.getElementById('close-modal').addEventListener('click', closeModal); document.getElementById('cancel-modal').addEventListener('click', closeModal); document.getElementById('task-modal').addEventListener('click', event => { if (event.target.id === 'task-modal') closeModal(); });
document.getElementById('task-form').addEventListener('submit', event => { event.preventDefault(); const data = { title: document.getElementById('task-name').value.trim(), notes: document.getElementById('task-notes').value.trim(), due: document.getElementById('task-date').value, time: document.getElementById('task-time').value, listId: document.getElementById('task-list-select').value }; if (editingId) Object.assign(state.tasks.find(task => task.id === editingId), data); else state.tasks.push({ ...data, id: crypto.randomUUID(), completed: false, created: Date.now() }); saveState(); closeModal(); render(); showToast(editingId ? 'Task updated' : 'Task added'); });
document.getElementById('delete-task').addEventListener('click', () => { state.tasks = state.tasks.filter(task => task.id !== editingId); saveState(); closeModal(); render(); showToast('Task deleted'); });
document.querySelectorAll('.filter-tab').forEach(tab => tab.addEventListener('click', () => { currentFilter = tab.dataset.filter; document.querySelectorAll('.filter-tab').forEach(item => item.classList.toggle('active', item === tab)); renderTasks(); renderStats(); })); document.getElementById('sort-button').addEventListener('click', () => { sortNewest = !sortNewest; document.querySelector('#sort-button strong').textContent = sortNewest ? 'date added' : 'due date'; renderTasks(); });
document.getElementById('add-list').addEventListener('click', () => { document.getElementById('list-modal').classList.remove('hidden'); document.getElementById('list-name').focus(); }); document.getElementById('close-list-modal').addEventListener('click', () => document.getElementById('list-modal').classList.add('hidden')); document.getElementById('cancel-list').addEventListener('click', () => document.getElementById('list-modal').classList.add('hidden')); document.getElementById('list-form').addEventListener('submit', event => { event.preventDefault(); const name = document.getElementById('list-name').value.trim(); if (!name) return; const list = { id: crypto.randomUUID(), name, color: 'peach' }; state.lists.push(list); saveState(); document.getElementById('list-modal').classList.add('hidden'); document.getElementById('list-form').reset(); render(); showToast('List created'); });
window.addEventListener('keydown', event => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); document.getElementById('search-toggle').focus(); } if (event.key === 'Escape') { closeModal(); document.getElementById('list-modal').classList.add('hidden'); } });
updateHeading(); render();
